with STG_SKVSSDT as (
select *
from 
    {{ref('TLTN_STU_SKVSSDT')}}
),

STG_TWDN_STU_ACCOMMODATION as (
SELECT
1 as ACCOMMODATION_ID,
SKVSSDT_SDAT_CODE_OPT_1,
SKVSSDT_TITLE,
'UNKNOWN' as ACCOMMODATION_GROUP
FROM STG_SKVSSDT
where SKVSSDT_SDAT_CODE_ENTITY = 'SKRHINS' 
and SKVSSDT_SDAT_CODE_ATTR = 'SKRHINS_SSDT_CODE_TTACOM' 
and SKVSSDT_STATUS_IND = 'A'
)

select * from STG_TWDN_STU_ACCOMMODATION