{​​​​​​​​{​​​​​​​​ config(materialized='table') }​​​​​​​​}​​​​​​​​

with STG_TWDN_STU_ACCOMMODATION as (
select*
from 
​{{ ref ('STG_TWDN_STU_ACCOMMODATION') }}

),

STG_TWDN_STU_ACCOMMODATION as (

SELECT ​​​​​​​​
1 as ACCOMMODATION_ID,
TLTN_STU_SKVSSDT.SKVSSDT_SDAT_CODE_OPT_1,
TLTN_STU_SKVSSDT.SKVSSDT_TITLE,
'UNKNOWN' as ACCOMMODATION_GROUP
FROM ​​​​​​​​TLTN_STU_SKVSSDT
where ​​​​​​​​TLTN_STU_SKVSSDT.SKVSSDT_SDAT_CODE_ENTITY = 'SKRHINS' 
and ​​​​​​​​TLTN_STU_SKVSSDT.SKVSSDT_SDAT_CODE_ATTR = 'SKRHINS_SSDT_CODE_TTACOM' 
and ​​​​​​​​TLTN_STU_SKVSSDT.SKVSSDT_STATUS_IND = 'A'

)

select * from TWDN_STU_ACCOMMODATION_DIM