with TLTN_STU_SKVSSDT as (
select * from ​​​​​​​​{{ ​​​​​​​​ref('TLTN_STU_SKVSSDT')}​​​​​​​​​​​​​​​}
),

stg_TWDN_STU_ACCOMMODATION as
(
SELECT ​​​​​​​​
TLTN_STU_SKVSSDT.SKVSSDT_SDAT_CODE_OPT_1,
​​​​​​​​TLTN_STU_SKVSSDT.SKVSSDT_TITLE
FROM ​​​​​​​​TLTN_STU_SKVSSDT
--where ​​​​​​​​TLTN_STU_SKVSSDT.SKVSSDT_SDAT_CODE_ENTITY = "SKRHINS" 
--and ​​​​​​​​TLTN_STU_SKVSSDT.SKVSSDT_SDAT_CODE_ATTR = "SKRHINS_SSDT_CODE_TTACOM" 
--and ​​​​​​​​TLTN_STU_SKVSSDT.SKVSSDT_STATUS_IND = "A"
)

select * from stg_TWDN_STU_ACCOMMODATION