USE WAREHOUSE WORKING_BI_STU_ANALYTICS_WAREHOUSE;

with TLTN_STU_SKVSSDT as
(
SELECT SKVSSDT_SDAT_CODE_ENTITY	,
SKVSSDT_SDAT_CODE_ATTR	,
SKVSSDT_SDAT_CODE_OPT_1,
Case When SKVSSDT_EFF_DATE = ' ' then Null Else Cast (SKVSSDT_EFF_DATE as timestamp) END AS SKVSSDT_EFF_DATE,
SKVSSDT_STATUS_IND	,
SKVSSDT_TITLE	,
SKVSSDT_SHORT_TITLE	,
SKVSSDT_USER	,
SKVSSDT_SDAT_CODE_OPT_2	,
SKVSSDT_SDAT_CODE_OPT_3	,
SKVSSDT_TERM_DATE	,
SKVSSDT_NCHG_DATE	,
SKVSSDT_DATA	,
Case When SKVSSDT_ACTIVITY_DATE = ' ' then Null Else Cast (SKVSSDT_ACTIVITY_DATE as timestamp) END AS SKVSSDT_ACTIVITY_DATE,
--to_timestamp_tz (SKVSSDT_ACTIVITY_DATE,'YYYY-MM-DD HH24:MI:SS')  AS SKVSSDT_ACTIVITY_DATE,
SKVSSDT_DATA_2	,
SKVSSDT_DATA_3	
FROM "WORKING_BI_STU_ANALYTICS"."BI_STU_STAGE"."SKVSSDT"
limit 10
)

select * from TLTN_STU_SKVSSDT