{{config (materialized = 'view')}}
USE WAREHOUSE WORKING_BI_STU_ANALYTICS_WAREHOUSE;
use schema BI_STU_STAGE;
create view Q_STU_ACCOMMODATION_DIM AS(
    select TLTN_STU_SKVSSDT.SKVSSDT_SDAT_CODE_OPT_1,TLTN_STU_SKVSSDT.SKVSSDT_TITLE
    FROM  "WORKING_BI_STU_ANALYTICS"."BI_STU_STAGE"."TLTN_STU_SKVSSDT"
    where SKVSSDT_SDAT_CODE_ENTITY = 'SKRHINS' 
    and SKVSSDT_SDAT_CODE_ATTR = 'SKRHINS_SSDT_CODE_TTACOM' 
    and SKVSSDT_STATUS_IND = 'A'
);